name: ackee_dart
description: Ackee tracker implemented in Dart
version: 0.0.1
homepage: https://github.com/marchellodev/ackee_dart
repository: https://github.com/marchellodev/ackee_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.3


dev_dependencies:
  lint: ^1.5.3
